global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "prometheus"
    fallback_scrape_protocol: PrometheusText0.0.4
    scrape_interval: 2s
    scrape_timeout: 2s
    http_sd_configs:
    - url: "http://localhost:7077/v1/prometheus-targets"
      refresh_interval: 5s
